# Generated by Django 5.1.1 on 2025-03-23 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedAmountFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('location', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='InNetworkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('location', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_entity_name', models.CharField(max_length=255)),
                ('reporting_entity_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('plan_id_type', models.CharField(max_length=50)),
                ('plan_id', models.CharField(max_length=50)),
                ('plan_market_type', models.CharField(max_length=50)),
                ('reporting_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_plans', to='insurance_data.reportingentity')),
            ],
        ),
        migrations.DeleteModel(
            name='ReportData',
        ),
        migrations.AddField(
            model_name='innetworkfile',
            name='reporting_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_network_files', to='insurance_data.reportingplan'),
        ),
        migrations.AddField(
            model_name='allowedamountfile',
            name='reporting_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_amount_files', to='insurance_data.reportingplan'),
        ),
    ]
